version: '3.7'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tu-newyozhy@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  client:
    image: ghcr.io/emtorresr/inventario-chasu-client:latest
    container_name: inventario-chasu-client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${HOST}`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
      - "traefik.http.services.client.loadbalancer.server.port=80"

  server:
    image: ghcr.io/emtorresr/inventario-chasu-server:latest
    container_name: inventario-chasu-server
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: chasu
      DB_PASSWORD: chasu123
      DB_NAME: inventario
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
      - "traefik.http.routers.server.middlewares=strip-api-prefix"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.services.server.loadbalancer.server.port=5000"
    expose:
      - "5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: inventario-chasu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
      MYSQL_USER: chasu
      MYSQL_PASSWORD: chasu123
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"

volumes:
  mysql-data:
